# Generated by Django 5.1 on 2025-09-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gallery/images/')),
                ('language', models.TextField()),
                ('demo', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
