# Generated by Django 5.1 on 2025-09-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='language',
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='bahasa', to='porto.tag'),
        ),
    ]
