# Generated by Django 5.1 on 2025-09-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0002_tag_remove_portofolio_language_portofolio_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon/images/')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='image',
            field=models.ImageField(upload_to='project/images/'),
        ),
    ]
