# Generated by Django 5.1 on 2025-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0003_skill_alter_portofolio_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project/images/')),
                ('tags', models.ManyToManyField(blank=True, related_name='job', to='porto.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
