# Generated by Django 5.1 on 2025-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porto', '0004_job_profil_delete_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='portofolio', to='porto.tag'),
        ),
    ]
